export const users: any[] = [];
export const orders: any[] = [];

export const products = [
  {
    id: "SHOE001",
    name: "Nike Air Force 1",
    brand: "Nike",
    brandLogo: "/brands/nike.svg",
    image: "/products/nike-air-force-1.png",
    price: 899,
    colors: ["White", "Black", "Red"],
  },
  {
    id: "SHOE002",
    name: "Nike Air Jordan 1",
    brand: "Nike",
    brandLogo: "/brands/nike.svg",
    image: "/products/air-jordan-1.png",
    price: 1299,
    colors: ["Red", "Black", "White"],
  },
  {
    id: "SHOE003",
    name: "Adidas Ultraboost",
    brand: "Adidas",
    brandLogo: "/brands/adidas.svg",
    image: "/products/adidas-ultraboost.png",
    price: 1099,
    colors: ["Black", "Grey", "Blue"],
  },
  {
    id: "SHOE004",
    name: "Adidas NMD R1",
    brand: "Adidas",
    brandLogo: "/brands/adidas.svg",
    image: "/products/adidas-nmd.png",
    price: 999,
    colors: ["White", "Black"],
  },
  {
    id: "SHOE005",
    name: "Puma RS-X",
    brand: "Puma",
    brandLogo: "/brands/puma.svg",
    image: "/products/puma-rsx.png",
    price: 799,
    colors: ["Grey", "Orange"],
  },
  {
    id: "SHOE006",
    name: "Puma Future Rider",
    brand: "Puma",
    brandLogo: "/brands/puma.svg",
    image: "/products/puma-future-rider.png",
    price: 749,
    colors: ["Blue", "White"],
  },
  {
    id: "SHOE007",
    name: "New Balance 574",
    brand: "New Balance",
    brandLogo: "/brands/new-balance.svg",
    image: "/products/nb-574.png",
    price: 699,
    colors: ["Grey", "Navy"],
  },
  {
    id: "SHOE008",
    name: "Asics Gel-Kayano",
    brand: "Asics",
    brandLogo: "/brands/asics.svg",
    image: "/products/asics-gel-kayano.png",
    price: 899,
    colors: ["Black", "Blue"],
  },
  {
    id: "SHOE009",
    name: "Reebok Classic Leather",
    brand: "Reebok",
    brandLogo: "/brands/reebok.svg",
    image: "/products/reebok-classic.png",
    price: 649,
    colors: ["White", "Black"],
  },
  {
    id: "SHOE010",
    name: "Converse Chuck Taylor",
    brand: "Converse",
    brandLogo: "/brands/converse.svg",
    image: "/products/converse-chuck.png",
    price: 599,
    colors: ["Black", "White", "Red"],
  },
];
